CREATE SEQUENCE SYSTEM_SEQUENCE_671C0627_A64F_49AA_AEBB_A3DDF0705A44 START WITH 1;

CREATE TABLE PUBLIC.PESSOA (
	ID                   uuid(128)   NOT NULL,
	NOME                 varchar(100)   ,
	DATANASC             date   ,
	APELIDO              varchar(20)   ,
	ENDERECO             varchar(100)   ,
	IMG                  varchar(20)   NOT NULL,
	CONSTRAINT PK_CONTATO PRIMARY KEY ( ID )
 );

CREATE TABLE PUBLIC.CONTATO (
	ID                   integer  DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_671C0627_A64F_49AA_AEBB_A3DDF0705A44) NOT NULL,
	TIPO                 integer   NOT NULL,
	DESCR                varchar(100)   NOT NULL,
	PESSOAID             uuid(128)   NOT NULL,
	CONSTRAINT CONSTRAINT_6 PRIMARY KEY ( ID )
 );

CREATE INDEX IDX_CONTATO ON PUBLIC.CONTATO ( PESSOAID );

ALTER TABLE PUBLIC.CONTATO ADD CONSTRAINT FK_CONTATO FOREIGN KEY ( PESSOAID ) REFERENCES PUBLIC.PESSOA( ID ) ON DELETE RESTRICT ON UPDATE RESTRICT;


